<?php

namespace Brocante\Bundle\BrocanteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationEmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationEmplacementRepository extends EntityRepository
{
}
