parameters:
#    brocante_user.example.class: Brocante\Bundle\UserBundle\Example

services:
#    brocante_user.example:
#        class: %brocante_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
